###
GET http://localhost:3000/users

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "nuevodeprueba@test.com",
    "password": "contrasena"
}

###
# @name token
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "nuevodeprueba@test.com",
    "password": "contrasena"
}

### Response varaible
@acces_token = {{token.response.body.token}}
@id_task = 65cae7348b23062f0254f885

###
GET http://localhost:3000/task
Authorization: Bearer {{acces_token}}


###65b86545f54b357811924bfd
POST http://localhost:3000/tasks
Authorization: Bearer {{acces_token}}
Content-Type: application/json

{
    "title": "Tarea para eliminar",
    "text": "Esta tarea es para eliminar"
}

###
PATCH http://localhost:3000/tasks/{{id_task}}
Authorization: Bearer {{acces_token}}
Content-Type: application/json

{
    "title": "Tarea para eliminar ¡AHORA!",
    "text": "Esta tarea es para eliminar"
}

###
DELETE http://localhost:3000/task/{{id_task}}
Authorization: Bearer {{acces_token}}