POST http://localhost:3000/task
Content-Type: application/json

{
    "title": "Tarea para eliminar",
    "text": "Esta tarea es para eliminar"
}

###
GET http://localhost:3000/task

###
PATCH http://localhost:3000/task/65cf8358cbf9fefae26fcee2
Content-Type: application/json

{
    "title": "Tarea modificandose",
    "text": "Esta tarea es para eliminar"
}