@uri_task = http://localhost:3000

###n
POST {{uri_task}}/signup
Content-Type: application/json

{
    "email": "newuser@hotmail.com",
    "password": ""
}

###
# @name token
POST {{uri_task}}/login
Content-Type: application/json

{
    "email": "newuser@hotmail.com",
    "password": "a1234567a"
}

###
@access_token = {{token.response.body.token}}
@id_task = xxxx

###
GET {{uri_task}}/task
Authorization: Bearer {{access_token}}

###
POST {{uri_task}}/task
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "Tarea con JWT",
    "text": "Mi primera tarea colocando JWT"
}

###
PATCH {{uri_task}}/task/65cf8358cbf9fefae26fcee2
Content-Type: application/json

{
    "title": "Tarea de prueba",
    "text": "Esta tarea es para eliminar"
}





###
